### ISSUE TITLE
Release binaries for Windows please

### ISSUE THREAD

**Issue by h4knet** [strukturag/heif-gimp-plugin#1]
Hello, your work seems awesome but would it work on Windows ? Is it possible to make a release with binaries ?

**Comment by mitchfoo** [comment]
The plug-in has just been integrated into GIMP, the next version 2.10.2 will include it and also
have a windows build.

**Comment by netro** [comment]
Awesome ! Thanks a lot for your work ! Hope it get released soon :)

**Comment by netro** [comment]
Sadly I must confirm what @peci1 said :(
I've looked in the "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins" folder and no plugins seems related with heif/heic. 

Gimp failed to open an heic file saying "unknown file type"..

@mitchfoo; Would you mind to relase a binary plugin for Windows ? It's been now two months :(

**Comment by netro** [comment]
but the release note says the opposite; is this a miss from the Gimp team ? https://www.gimp.org/news/2018/05/20/gimp-2-10-2-released/

**Comment by mitchfoo** [comment]
Sadly, it's a mis-build in the windows installer. We are working on an updated installer.

**Comment by KrasnayaPloshchad** [comment]
Fixed in 2.10.4.

**Comment by mijangosaa** [comment]
I need to download the compiled plug-in on a machine that can't be updated to the latest version of GIMP. Can someone post the compiled library or link to it.

**Comment by netro** [comment]
Hi @mijangosaa, 

Here : https://we.tl/t-ut83oPIeWa

Regards,
