### ISSUE TITLE
Build fails with main.c:367:3: error: ‘gimp_drawable_detach’ is deprecated [-Werror=deprecated-declarations]

### ISSUE THREAD

**Issue by felixbecker2** [strukturag/heif-gimp-plugin#2]
When building on Arch Linux (using the AUR package http://aur.archlinux.org/packages/heif-gimp-plugin), I get the following error:

    [...]
    main.c:367:3: error: ‘gimp_drawable_detach’ is deprecated [-Werror=deprecated-declarations]
       gimp_drawable_detach(drawable);
       ^~~~~~~~~~~~~~~~~~~~
    In file included from /usr/include/gimp-2.0/libgimp/gimp.h:41,
                     from main.c:26:
    /usr/include/gimp-2.0/libgimp/gimpdrawable.h:53:16: note: declared here
     void           gimp_drawable_detach                 (GimpDrawable  *drawable);
                    ^~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    make[2]: *** [Makefile:436: heif_gimp_plugin-main.o] Error 1
    make[2]: Leaving directory '/var/tmp/yaourt-tmp-felics/aur-heif-gimp-plugin/src/heif-gimp-plugin-libheif-v1.1.0/src'
    make[1]: *** [Makefile:402: all-recursive] Error 1
    make[1]: Leaving directory '/var/tmp/yaourt-tmp-felics/aur-heif-gimp-plugin/src/heif-gimp-plugin-libheif-v1.1.0'
    make: *** [Makefile:343: all] Error 2

Maybe the deprecated declaration should be fixed or `-Werror=deprecated-declarations` should be explicitly disabled somewhere down in the Makefile(s).

**Comment by fancycode** [comment]
Thanks for reporting!
